import { kpis, chartSeries } from '../data/demoMachines';
import { activityFeed } from '../data/report';
import { useDemoFlow } from '../state/DemoFlowContext';
import { KpiCard } from '../components/KpiCard';
import { StatusBadge } from '../components/StatusBadge';
import { TrendChart } from '../components/TrendChart';
import { navigate } from '../components/AppShell';

export function Dashboard() {
  const { selectedMachine, flowState, notification, lastAction, simulateHighRisk, simulateAcknowledgement, simulateNoResponse } = useDemoFlow();
  const active = flowState !== 'idle';
  return <div className="dashboard-page page-stack">
    <section className="page-heading dashboard-heading"><div><div className="eyebrow">OPERATIONS CONTROL CENTER / 03 OCT 2026</div><h1>From signal to <em>verified response.</em></h1><p>Predictive machine-health analysis connected to explainable AI reasoning and autonomous workflow automation.</p></div><div className="heading-actions"><span className="demo-label"><span className="status-dot pulse"></span>DEMO DATA ACTIVE</span><button className="button button-lime" onClick={simulateHighRisk}>SIMULATE HIGH-RISK EVENT <span>↗</span></button></div></section>
    <div className="disclosure-strip"><span className="disclosure-icon">i</span><span><strong>Research / hackathon prototype.</strong> Demo data derived from public predictive-maintenance dataset structure. No live factory telemetry.</span><span className="disclosure-end">CONTROLLED DEMONSTRATION</span></div>
    <section className="kpi-grid">{kpis.map((kpi) => <KpiCard key={kpi.label} {...kpi} />)}</section>
    <section className="dashboard-grid main-grid">
      <article className="panel risk-focus-panel"><div className="panel-header"><div><span className="eyebrow">PRIORITY QUEUE / MACHINE 01</span><h2>High-risk machine focus</h2></div><StatusBadge value={selectedMachine.risk} /></div><div className="focus-machine"><div className="focus-ring"><span>{selectedMachine.health}</span><small>HEALTH</small></div><div className="focus-copy"><div className="machine-headline"><span className="machine-id">{selectedMachine.id}</span><span className="focus-type">{selectedMachine.type}</span></div><h3>Intervention threshold reached</h3><p>{selectedMachine.latestAnalysis}</p><div className="focus-meta"><span><b>↘ {selectedMachine.trend}</b> degradation</span><span><b>{selectedMachine.cycle}</b></span><span><b>{selectedMachine.operatingTime}</b></span></div></div></div><div className="focus-footer"><span><span className="status-dot"></span>Latest analysis: 14:32:10</span><button className="text-button" onClick={() => navigate('/decision')}>OPEN DECISION CENTER ↗</button></div></article>
      <article className="panel activity-panel"><div className="panel-header"><div><span className="eyebrow">EVENT STREAM / SIMULATED</span><h2>System activity</h2></div><span className="live-pill"><i></i>LIVE</span></div><div className="activity-list">{activityFeed.map((event) => <div className="activity-item" key={event.time + event.label}><span className={`activity-dot ${event.tone}`}></span><div><strong>{event.label}</strong><small>{event.source}</small></div><time>{event.time}</time></div>)}</div><button className="panel-link" onClick={() => navigate('/workflow')}>VIEW WORKFLOW MONITOR <span>→</span></button></article>
      <article className="panel trend-overview"><div className="panel-header"><div><span className="eyebrow">M-204 / SENSOR TREND</span><h2>Degradation trajectory</h2></div><span className="chart-updated">LAST 24 HOURS</span></div><TrendChart kind="vibration" values={chartSeries.vibration} title="Vibration RMS" unit="normalized demonstration trace" /><div className="trend-caption"><span><i className="legend-dot lime"></i>Vibration RMS</span><strong>+18.4%</strong><span className="muted">since baseline</span></div></article>
      <article className="panel response-panel"><div className="panel-header"><div><span className="eyebrow">AUTONOMOUS RESPONSE / n8n</span><h2>Action status</h2></div><span className={`state-chip ${active ? flowState : 'idle'}`}>{active ? flowState.replaceAll('_', ' ').toUpperCase() : 'READY'}</span></div><div className="response-status"><div className="response-icon">{flowState === 'resolved' ? '✓' : flowState === 'escalated' ? '!' : active ? 'Ⅱ' : '→'}</div><div><strong>{active ? notification : 'No active workflow event'}</strong><p>{lastAction}</p></div></div>{active && flowState !== 'resolved' && flowState !== 'escalated' ? <div className="response-actions"><button className="button button-small button-lime" onClick={simulateAcknowledgement}>ACKNOWLEDGE</button><button className="button button-small button-outline" onClick={simulateNoResponse}>NO RESPONSE</button></div> : <button className="panel-link" onClick={simulateHighRisk}>{flowState === 'resolved' || flowState === 'escalated' ? 'REPLAY CONTROLLED DEMO' : 'START CONTROLLED DEMO'} <span>→</span></button>}</article>
    </section>
  </div>;
}
