import { useDemoFlow } from '../state/DemoFlowContext';
import { DecisionPanel } from '../components/DecisionPanel';
import { StatusBadge } from '../components/StatusBadge';
import { navigate } from '../components/AppShell';

export function DecisionCenter() {
  const { flowState, simulateHighRisk } = useDemoFlow();
  return <div className="page-stack"><section className="page-heading"><div><div className="eyebrow">RESPONSE / EXPLAINABLE DECISION</div><h1>AI decision center</h1><p>Separate the predictive signal from the operational reasoning that turns it into a workflow.</p></div><div className="heading-actions"><StatusBadge value={flowState === 'idle' ? 'READY TO EXECUTE' : 'WORKFLOW ACTIVE'} /><button className="button button-lime" onClick={simulateHighRisk}>SIMULATE HIGH-RISK EVENT ↗</button></div></section><div className="layer-strip"><div><span className="layer-number">01</span><div><strong>PREDICTIVE MODEL OUTPUT</strong><small>Machine-risk information</small></div></div><span>→</span><div><span className="layer-number lime">02</span><div><strong>AI REASONING</strong><small>Operational interpretation</small></div></div><span>→</span><div><span className="layer-number amber">03</span><div><strong>DECISION</strong><small>Human approval gate</small></div></div></div><section className="panel decision-panel-wrap"><DecisionPanel /></section><section className="decision-bottom-grid"><article className="panel approval-panel"><div className="panel-header"><div><span className="eyebrow">DECISION CONTRACT</span><h2>Accountability stays visible</h2></div><span className="contract-icon">◎</span></div><div className="contract-row"><span>RECOMMENDATION</span><strong>SCHEDULE MAINTENANCE INSPECTION</strong></div><div className="contract-row"><span>HUMAN APPROVAL</span><StatusBadge value="REQUIRED" tone="warning" /></div><div className="contract-row"><span>EXECUTION MODE</span><strong className="muted">CONTROLLED DEMO ONLY</strong></div><button className="panel-link" onClick={() => navigate('/workflow')}>TRACE THROUGH n8n WORKFLOW <span>→</span></button></article><article className="panel boundary-panel"><div className="panel-header"><div><span className="eyebrow">MODEL BOUNDARY</span><h2>What is not claimed</h2></div></div><div className="boundary-copy"><p>This prototype does not claim model accuracy, live telemetry, production deployment, or autonomous physical actuation.</p><div className="boundary-tags"><span>NO LIVE TELEMETRY</span><span>NO FABRICATED METRICS</span><span>NO FACTORY DEPLOYMENT</span></div></div></article></section></div>;
}
